/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov;

import java.util.List;
import org.junit.jupiter.api.Test;
import ru.nsu.fit.makhov.multithread.MultithreadPrimeChecker;

class MultithreadingTest {
    @Test
    void t1() {
        PrimeChecker primeChecker = new MultithreadPrimeChecker();
        System.out.println(primeChecker.isPrime(List.of(6997901, 6997927, 6997937, 6997967, 6998009, 6998029, 6998039, 6998051, 6998053)));
    }
}
