/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.pizzeria;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class Pizzeria {



  public static void main(String[] args) {
    PizzeriaManager pizzeriaManager = new PizzeriaSetup(2, 3).setup();
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {
      String comm = reader.readLine();
      orderListener.acceptTheOrder(comm);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
