/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.heapsort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class HeapSortTests {
  @Test
  void testHeapsort() {
    int[] arr = {5, 4, 3, 2, 1};
    int[] sortedArr = {1, 2, 3, 4, 5};
    HeapSort.sort(arr);
    assertArrayEquals(sortedArr, arr, "Not equal");
  }
}
