/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.pizzeria;

import org.junit.jupiter.api.Test;

class PizzeriaTest {
    @Test
    void appHasAGreeting() {
        CommandParser.parseCommand("[123 122] [212 333]");
    }
}
