/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.heapsort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void testHeapsort1() {
    int[] arr = {5, 4, 3, 2, 1};
    int[] sortedArr = {1, 2, 3, 4, 5};
    HeapSort heapSort = new HeapSort(arr);
    heapSort.sort();
    assertArrayEquals(sortedArr, heapSort.getArr(), "Not equal");
  }
}
