/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.calc;


import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class CalcTests {
  ExpirationListener expirationListener = new ExpirationListener();

  @Test
  public void calcTest() {
    Assertions.assertEquals(0.0, expirationListener.calcExpiration("sin + - 1 2 1"));
  }
}
