/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.stack;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class StackTests {

  @Test
  public void stackTest1() {
    Integer[] assertArray1 = {2};
    Integer[] assertArray2 = {2, 7};
    Integer[] assertArray3 = {2, 7, 4, 8};
    Integer[] assertArray4 = {2, 7, 4};
    Integer[] assertArray5 = {7, 4};
    Stack<Integer> stack = new Stack<>();
    stack.push(2);
    Assertions.assertArrayEquals(assertArray1, stack.toArray());
    stack.push(7);
    Assertions.assertArrayEquals(assertArray2, stack.toArray());
    stack.pushStack(4, 8);
    Assertions.assertArrayEquals(assertArray3, stack.toArray());
    Assertions.assertEquals(8, stack.pop());
    Assertions.assertArrayEquals(assertArray4, stack.toArray());
    Assertions.assertArrayEquals(assertArray5, stack.popStack(2));
    Assertions.assertArrayEquals(assertArray1, stack.toArray());
    Assertions.assertEquals(1, stack.count());
  }
}
