/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.calc;


import org.junit.jupiter.api.Test;

class CalcTests {
  ExpirationListener expirationListener = new ExpirationListener();

  @Test
  public void calcTest() {
    System.out.println(expirationListener.calcExpiration("son 0"));
  }
}
