/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.substring;

import java.util.Arrays;
import java.util.Collections;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

class SubstringFinderTests {

  private static SubstringFinder substringFinder;

  @BeforeAll
  public static void init() {
    substringFinder = new SubstringFinder();
  }

  @Test
  public void substringFinderOneCharTest() throws FileNotFoundException {
    Assertions.assertEquals(
        Collections.emptyList(),
        substringFinder.findSubstring("src/test/resources/input.txt", "'"));
    Assertions.assertEquals(Arrays.asList(0, 25, 51, 90, 116, 141),
        substringFinder.findSubstring("src/test/resources/input.txt", "N"));
    Assertions.assertEquals(
        Arrays.asList(19, 21, 43, 64, 70, 87, 109, 169, 175),
        substringFinder.findSubstring("src/test/resources/input.txt", "u"));
    Assertions.assertEquals(
        Arrays.asList(24, 50, 89, 115, 140),
        substringFinder.findSubstring("src/test/resources/input.txt", "\n"));
  }

  @Test
  public void substringFinderWordTest() throws FileNotFoundException {
    Assertions.assertEquals(
        Arrays.asList(0, 25, 51, 90, 116, 141),
        substringFinder.findSubstring("src/test/resources/input.txt", "Never gonna"));
    Assertions.assertEquals(
        Collections.emptyList(), substringFinder.findSubstring("src/test/resources/input.txt",
            "We're no strangers to love"));
  }

  @Test
  public void SubstringFinderFileNotFoundExceptionTest() {
    Assertions.assertThrows(FileNotFoundException.class,
        () -> substringFinder.findSubstring("BibaBobovich", "biba"));
  }
}
