/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.substring;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

class SubstringFinderTest {
  @Test
  public void substringFinderTest1() throws FileNotFoundException {
    SubstringFinder substringFinder =
        new SubstringFinder(
            "src/test/resources/input.txt"); //тут относительный путь нужен
    System.out.println(substringFinder.findSubstring("Whe"));
  }
}
