/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.substring;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

class SubstringFinderTest {
  @Test
  public void substringFinderTest1() throws FileNotFoundException {
    SubstringFinder substringFinder =
        new SubstringFinder(
            "D:\\OOP\\OOP-task-1-3-1\\Task_1_3_1\\lib\\src\\test\\resources\\input.txt");
    System.out.println(substringFinder.findSubstring("Whe"));
  }
}
