/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.substring;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
