/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.makhov.substring;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class SubstringFinder {

  public final Scanner scanner;

  public SubstringFinder(String fileName) throws FileNotFoundException {
    File file = new File(fileName);
    this.scanner = new Scanner(file);
  }

  public List<Integer> findSubstring(String substring) {
    int pointer = 0;
    int nSubstring = 0;
    List<Integer> listSubstr = new ArrayList<>();
    scanner.useDelimiter("");
    for (int i = 0; scanner.hasNext(); i++) {
      char currFile = scanner.next().charAt(0);
      char currStr = substring.charAt(pointer);
      if (pointer == 0 && (currFile == currStr)){
        nSubstring = i;
        pointer++;
      }
      else if (pointer > 0 && pointer < substring.length() && currFile == currStr) pointer++;
      else if (currFile != currStr) pointer = 0;
      else if (pointer == substring.length()){
        pointer = 0;
        listSubstr.add(nSubstring);
      }
    }
    return listSubstr;
  }
}
